# Generated by Django 3.1.3 on 2020-12-02 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0002_userprofile_default_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='paid_until',
            field=models.DateField(blank=True, null=True),
        ),
    ]
