# Generated by Django 3.1.3 on 2020-12-28 01:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_userprofile_paid_until'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='default_email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
