# Generated by Django 3.1.3 on 2020-11-18 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20201118_0006'),
    ]

    operations = [
        migrations.AlterField(
            model_name='membership',
            name='membership_type',
            field=models.CharField(blank=True, default='Unlimited', max_length=10, null=True),
        ),
    ]
