# Generated by Django 3.1.3 on 2020-12-27 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='subscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fixed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('name', models.CharField(blank=True, max_length=254, null=True)),
            ],
        ),
    ]
