# Generated by Django 3.1.3 on 2020-11-15 02:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='takenat',
        ),
    ]
