# Generated by Django 3.1.3 on 2020-12-28 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20201228_2345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='stripe_plan_id',
            field=models.CharField(blank=True, default='n/a', max_length=254, null=True),
        ),
    ]
