# Generated by Django 3.1.3 on 2020-11-18 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20201118_0006'),
        ('products', '0003_product_allowed_memberships'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='allowed_memberships',
            field=models.ManyToManyField(blank=True, null=True, to='membership.Membership'),
        ),
    ]
