# Generated by Django 3.1.3 on 2020-11-18 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membership', '0002_auto_20201118_0006'),
        ('products', '0005_remove_product_allowed_memberships'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='allowed_memberships',
            field=models.ManyToManyField(to='membership.Membership'),
        ),
    ]
